### PR TITLE
Windows

### PR DESCRIPTION
**Pull request by ethansocal**

### CODE REVIEW

**Review by mustafaquraish — APPROVED** [review]

**Review by briancohan — COMMENTED** [review]
I know that it's perfectly valid python to put the import down there, but I think I might prefer to see all the imports at the top. This can (and probably should) be put in a try/except block at the top. 

I also think we should avoid an `underline red bold flashing` message that indicates that our project isn't working how we'd prefer.

Lastly, I'm going to suggest using [`sys.modules`](https://docs.python.org/3/library/sys.html#sys.modules) to see if `textual` is imported or not rather than creating another variable. I might also suggest that this take place in a new function to override `opts["no_display"]` if `textual` is not loaded. I'd keep `parse_arguments()` as purely processing `sys.argv` so that we can write tests for it, but maybe have the top of `main()` say:

```python
def main() -> None:
    """Run the application."""
    opts = parse_arguments()
    opts = apply_overrides(opts)
    ...
```
The `apply_overrides()` function can be expanded as necessary to check for conditions we encounter in the future.

**Comment by VagishVela** [comment]
My understanding is this is for those who aren't using WSL on Windows. Well in that case I would update the error message to not be red and say, Textual isn't supported on Windows yet so defaulting to no display mode. Or something like that.

We may support other TUIs in the future, and at that point the lack of support on Windows without WSL will be solved.

**Comment by VagishVela** [comment]
@what-the-python/maintainers I personally don't like stale PRs, so vote on this using 👍🏾  or 👎🏾 on whether this should be closed or merged.

**Comment by mustafaquraish** [comment]
I think the changes here are reasonable. Vote for merge, we can improve upon it later as needed

**Review by VagishVela — APPROVED** [review]
LGTM due to 3 👍🏾

**Pull request merged**
