### PR TITLE
Add command line option to clear the HTTP cache

### PR DESCRIPTION
**Pull request by mustafaquraish**
Solves #87

Perhaps the design could be improved. Currently the `StackOverflowFinder()` takes a boolean in the constructor to tell it to clear the cache before performing any requests.

### CODE REVIEW

**Comment by briancohan** [comment]
should be able to call `wtpython --clear-cache` and have it work

**Comment by mustafaquraish** [comment]
> should be able to call wtpython --clear-cache and have it work

Why do you think it's necessary to be able to call it this way? This complicates things since we'd need to have a separate place to now instantiate the `CachedSession()` just to delete the cache. I don't want to just use `shtul.rmtree()` to delete the file structure for the cache directly because that seems crude. Personally I think just being able to specify the `--clear-cache` argument when running to clear the cache and then run seems reasonable.

**Comment by briancohan** [comment]
I want to be able to see that the cache was cleared. perhaps I had a lot of issues and I have a lot of results in there that I want to clean up.

**Comment by mustafaquraish** [comment]
> I want to be able to see that the cache was cleared. perhaps I had a lot of issues and I have a lot of results in there that I want to clean up.

Why do you mean you want to "see the cache was cleared"? You can test this out by just disabling your internet and seeing that once you pass in the flag the cache gets cleared and no requests go through.

Worst case you can always just manually delete the cache by `rm -r ~/.wtpython_cache`

**Review by VagishVela — APPROVED** [review]
LGTM

**Pull request merged**
